/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AlertChannelSubscriptionCreate {
    /**
    * You can either pass a checkId or a groupId, but not both.
    */
    'checkId'?: string;
    /**
    * You can either pass a checkId or a groupId, but not both.
    */
    'groupId'?: number;
    'activated': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "checkId",
            "baseName": "checkId",
            "type": "string"
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "number"
        },
        {
            "name": "activated",
            "baseName": "activated",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return AlertChannelSubscriptionCreate.attributeTypeMap;
    }
}

