/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AlertSettingsReminders {
    /**
    * How many reminders to send out after the initial alert notification.
    */
    'amount'?: AlertSettingsReminders.AmountEnum = AlertSettingsReminders.AmountEnum.NUMBER_0;
    /**
    * At what interval the reminders should be send.
    */
    'interval'?: AlertSettingsReminders.IntervalEnum = AlertSettingsReminders.IntervalEnum.NUMBER_5;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "AlertSettingsReminders.AmountEnum"
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "AlertSettingsReminders.IntervalEnum"
        }    ];

    static getAttributeTypeMap() {
        return AlertSettingsReminders.attributeTypeMap;
    }
}

export namespace AlertSettingsReminders {
    export enum AmountEnum {
        NUMBER_0 = <any> 0,
        NUMBER_1 = <any> 1,
        NUMBER_2 = <any> 2,
        NUMBER_3 = <any> 3,
        NUMBER_4 = <any> 4,
        NUMBER_5 = <any> 5,
        NUMBER_100000 = <any> 100000
    }
    export enum IntervalEnum {
        NUMBER_5 = <any> 5,
        NUMBER_10 = <any> 10,
        NUMBER_15 = <any> 15,
        NUMBER_30 = <any> 30
    }
}
