/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AlertChanelSubscription } from './alertChanelSubscription';

export class AlertChannel {
    'id'?: number;
    /**
    * The type of alert channel, i.e. EMAIL or SLACK.
    */
    'type'?: string;
    'config'?: object;
    /**
    * All checks subscribed to this channel.
    */
    'subscriptions'?: Array<AlertChanelSubscription>;
    'sendRecovery'?: boolean;
    'sendFailure'?: boolean;
    'sendDegraded'?: boolean;
    /**
    * Determines if an alert should be send for expiring SSL certificates.
    */
    'sslExpiry'?: boolean = false;
    /**
    * At what moment in time to start alerting on SSL certificates.
    */
    'sslExpiryThreshold'?: number = 30;
    'createdAt'?: Date;
    'updatedAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "object"
        },
        {
            "name": "subscriptions",
            "baseName": "subscriptions",
            "type": "Array<AlertChanelSubscription>"
        },
        {
            "name": "sendRecovery",
            "baseName": "sendRecovery",
            "type": "boolean"
        },
        {
            "name": "sendFailure",
            "baseName": "sendFailure",
            "type": "boolean"
        },
        {
            "name": "sendDegraded",
            "baseName": "sendDegraded",
            "type": "boolean"
        },
        {
            "name": "sslExpiry",
            "baseName": "sslExpiry",
            "type": "boolean"
        },
        {
            "name": "sslExpiryThreshold",
            "baseName": "sslExpiryThreshold",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return AlertChannel.attributeTypeMap;
    }
}

