/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AlertSettingsRunBasedEscalation {
    /**
    * After how many failed consecutive check runs an alert notification should be send.
    */
    'failedRunThreshold'?: AlertSettingsRunBasedEscalation.FailedRunThresholdEnum = AlertSettingsRunBasedEscalation.FailedRunThresholdEnum.NUMBER_1;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "failedRunThreshold",
            "baseName": "failedRunThreshold",
            "type": "AlertSettingsRunBasedEscalation.FailedRunThresholdEnum"
        }    ];

    static getAttributeTypeMap() {
        return AlertSettingsRunBasedEscalation.attributeTypeMap;
    }
}

export namespace AlertSettingsRunBasedEscalation {
    export enum FailedRunThresholdEnum {
        NUMBER_1 = <any> 1,
        NUMBER_2 = <any> 2,
        NUMBER_3 = <any> 3,
        NUMBER_4 = <any> 4,
        NUMBER_5 = <any> 5
    }
}
