/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AlertChanelSubscription } from './alertChanelSubscription';

export class AlertChannelCreate {
    /**
    * All checks subscribed to this channel.
    */
    'subscriptions'?: Array<AlertChanelSubscription>;
    'type': AlertChannelCreate.TypeEnum;
    'config': object;
    'sendRecovery'?: boolean;
    'sendFailure'?: boolean;
    'sendDegraded'?: boolean;
    /**
    * Determines if an alert should be send for expiring SSL certificates.
    */
    'sslExpiry'?: boolean = false;
    /**
    * At what moment in time to start alerting on SSL certificates.
    */
    'sslExpiryThreshold'?: number = 30;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subscriptions",
            "baseName": "subscriptions",
            "type": "Array<AlertChanelSubscription>"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AlertChannelCreate.TypeEnum"
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "object"
        },
        {
            "name": "sendRecovery",
            "baseName": "sendRecovery",
            "type": "boolean"
        },
        {
            "name": "sendFailure",
            "baseName": "sendFailure",
            "type": "boolean"
        },
        {
            "name": "sendDegraded",
            "baseName": "sendDegraded",
            "type": "boolean"
        },
        {
            "name": "sslExpiry",
            "baseName": "sslExpiry",
            "type": "boolean"
        },
        {
            "name": "sslExpiryThreshold",
            "baseName": "sslExpiryThreshold",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AlertChannelCreate.attributeTypeMap;
    }
}

export namespace AlertChannelCreate {
    export enum TypeEnum {
        Email = <any> 'EMAIL',
        Slack = <any> 'SLACK',
        Webhook = <any> 'WEBHOOK',
        Sms = <any> 'SMS',
        Pagerduty = <any> 'PAGERDUTY',
        Opsgenie = <any> 'OPSGENIE'
    }
}
