/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Assertion {
    'source'?: Assertion.SourceEnum;
    'property'?: string = '';
    'comparison'?: Assertion.ComparisonEnum;
    'target'?: string = '';

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "source",
            "baseName": "source",
            "type": "Assertion.SourceEnum"
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "string"
        },
        {
            "name": "comparison",
            "baseName": "comparison",
            "type": "Assertion.ComparisonEnum"
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Assertion.attributeTypeMap;
    }
}

export namespace Assertion {
    export enum SourceEnum {
        StatusCode = <any> 'STATUS_CODE',
        JsonBody = <any> 'JSON_BODY',
        Headers = <any> 'HEADERS',
        TextBody = <any> 'TEXT_BODY',
        ResponseTime = <any> 'RESPONSE_TIME'
    }
    export enum ComparisonEnum {
        Equals = <any> 'EQUALS',
        NotEquals = <any> 'NOT_EQUALS',
        HasKey = <any> 'HAS_KEY',
        NotHasKey = <any> 'NOT_HAS_KEY',
        HasValue = <any> 'HAS_VALUE',
        NotHasValue = <any> 'NOT_HAS_VALUE',
        IsEmpty = <any> 'IS_EMPTY',
        NotEmpty = <any> 'NOT_EMPTY',
        GreaterThan = <any> 'GREATER_THAN',
        LessThan = <any> 'LESS_THAN',
        Contains = <any> 'CONTAINS',
        NotContains = <any> 'NOT_CONTAINS',
        IsNull = <any> 'IS_NULL',
        NotNull = <any> 'NOT_NULL'
    }
}
