/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AlertSettingsReminders } from './alertSettingsReminders';
import { AlertSettingsRunBasedEscalation } from './alertSettingsRunBasedEscalation';
import { AlertSettingsSSLCertificates } from './alertSettingsSSLCertificates';
import { AlertSettingsTimeBasedEscalation } from './alertSettingsTimeBasedEscalation';

/**
* Alert settings.
*/
export class CheckGroupAlertSettings {
    /**
    * Determines what type of escalation to use.
    */
    'escalationType'?: CheckGroupAlertSettings.EscalationTypeEnum = CheckGroupAlertSettings.EscalationTypeEnum.RunBased;
    'runBasedEscalation'?: AlertSettingsRunBasedEscalation;
    'timeBasedEscalation'?: AlertSettingsTimeBasedEscalation;
    'reminders'?: AlertSettingsReminders;
    'sslCertificates'?: AlertSettingsSSLCertificates;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "escalationType",
            "baseName": "escalationType",
            "type": "CheckGroupAlertSettings.EscalationTypeEnum"
        },
        {
            "name": "runBasedEscalation",
            "baseName": "runBasedEscalation",
            "type": "AlertSettingsRunBasedEscalation"
        },
        {
            "name": "timeBasedEscalation",
            "baseName": "timeBasedEscalation",
            "type": "AlertSettingsTimeBasedEscalation"
        },
        {
            "name": "reminders",
            "baseName": "reminders",
            "type": "AlertSettingsReminders"
        },
        {
            "name": "sslCertificates",
            "baseName": "sslCertificates",
            "type": "AlertSettingsSSLCertificates"
        }    ];

    static getAttributeTypeMap() {
        return CheckGroupAlertSettings.attributeTypeMap;
    }
}

export namespace CheckGroupAlertSettings {
    export enum EscalationTypeEnum {
        RunBased = <any> 'RUN_BASED',
        TimeBased = <any> 'TIME_BASED'
    }
}
