/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CheckAlert {
    /**
    * The unique ID of this alert.
    */
    'id'?: string;
    /**
    * The name of the check.
    */
    'name': string;
    /**
    * The ID of check this alert belongs to.
    */
    'checkId'?: string;
    /**
    * The type of alert.
    */
    'alertType'?: string;
    /**
    * The type of the check.
    */
    'checkType'?: CheckAlert.CheckTypeEnum;
    /**
    * What data center location this check alert was triggered from.
    */
    'runLocation'?: string;
    /**
    * Describes the time it took to execute relevant parts of this check. Any setup timeor system time needed to start executing this check in the Checkly backend is not part of this.
    */
    'responseTime'?: number;
    /**
    * Any specific error messages that were part of the failing check triggering the alert.
    */
    'error'?: string;
    /**
    * The status code of the response. Only applies to API checks.
    */
    'statusCode'?: string;
    /**
    * The date and time this check alert was created.
    */
    'createdAt'?: string;
    /**
    * The date and time this check alert was started.
    */
    'startedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "checkId",
            "baseName": "checkId",
            "type": "string"
        },
        {
            "name": "alertType",
            "baseName": "alertType",
            "type": "string"
        },
        {
            "name": "checkType",
            "baseName": "checkType",
            "type": "CheckAlert.CheckTypeEnum"
        },
        {
            "name": "runLocation",
            "baseName": "runLocation",
            "type": "string"
        },
        {
            "name": "responseTime",
            "baseName": "responseTime",
            "type": "number"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "startedAt",
            "baseName": "startedAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CheckAlert.attributeTypeMap;
    }
}

export namespace CheckAlert {
    export enum CheckTypeEnum {
        Browser = <any> 'BROWSER',
        Api = <any> 'API'
    }
}
