/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ConflictError {
    'statusCode': ConflictError.StatusCodeEnum;
    'error': ConflictError.ErrorEnum;
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "ConflictError.StatusCodeEnum"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "ConflictError.ErrorEnum"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ConflictError.attributeTypeMap;
    }
}

export namespace ConflictError {
    export enum StatusCodeEnum {
        NUMBER_409 = <any> 409
    }
    export enum ErrorEnum {
        Conflict = <any> 'Conflict'
    }
}
