/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GroupAssignment {
    'id': string;
    /**
    * The ID of the group.
    */
    'groupId': number;
    /**
    * The ID of the assigned private location.
    */
    'privateLocationId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "number"
        },
        {
            "name": "privateLocationId",
            "baseName": "privateLocationId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GroupAssignment.attributeTypeMap;
    }
}

