/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MaintenanceWindow {
    /**
    * The id of the maintenance window.
    */
    'id': number;
    /**
    * The maintenance window name.
    */
    'name': string;
    /**
    * The names of the checks and groups maintenance window should apply to.
    */
    'tags'?: Array<string>;
    /**
    * The start date of the maintenance window.
    */
    'startsAt': string;
    /**
    * The end date of the maintenance window.
    */
    'endsAt': string;
    /**
    * The repeat interval of the maintenance window from the first occurance.
    */
    'repeatInterval'?: number;
    /**
    * The repeat strategy for the maintenance window.
    */
    'repeatUnit': string;
    /**
    * The end date where the maintenance window should stop repeating.
    */
    'repeatEndsAt'?: string;
    /**
    * The creation date of the maintenance window.
    */
    'createdAt': string;
    /**
    * The last date that the maintenance window was updated.
    */
    'updatedAt': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "startsAt",
            "baseName": "startsAt",
            "type": "string"
        },
        {
            "name": "endsAt",
            "baseName": "endsAt",
            "type": "string"
        },
        {
            "name": "repeatInterval",
            "baseName": "repeatInterval",
            "type": "number"
        },
        {
            "name": "repeatUnit",
            "baseName": "repeatUnit",
            "type": "string"
        },
        {
            "name": "repeatEndsAt",
            "baseName": "repeatEndsAt",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MaintenanceWindow.attributeTypeMap;
    }
}

