/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ReportingAggregate {
    /**
    * Success ratio of the check over selected date range. Percentage is in decimal form.
    */
    'successRatio': number;
    /**
    * Average response time of the check over selected date range in milliseconds.
    */
    'avg': number;
    /**
    * P95 response time of the check over selected date range in milliseconds.
    */
    'p95': number;
    /**
    * P99 response time of the check over selected date range in milliseconds.
    */
    'p99': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "successRatio",
            "baseName": "successRatio",
            "type": "number"
        },
        {
            "name": "avg",
            "baseName": "avg",
            "type": "number"
        },
        {
            "name": "p95",
            "baseName": "p95",
            "type": "number"
        },
        {
            "name": "p99",
            "baseName": "p99",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ReportingAggregate.attributeTypeMap;
    }
}

