/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TooManyRequestsError {
    'statusCode': TooManyRequestsError.StatusCodeEnum;
    'error': TooManyRequestsError.ErrorEnum;
    'message'?: string;
    'attributes'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "TooManyRequestsError.StatusCodeEnum"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "TooManyRequestsError.ErrorEnum"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return TooManyRequestsError.attributeTypeMap;
    }
}

export namespace TooManyRequestsError {
    export enum StatusCodeEnum {
        NUMBER_429 = <any> 429
    }
    export enum ErrorEnum {
        TooManyRequests = <any> 'Too Many Requests'
    }
}
