/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* [DEPRECATED] `sslCertificates` is deprecated and is not longer used. Please ignore it, will be removed in a future version.
*/
export class AlertSettingsSSLCertificates {
    /**
    * Determines if alert notifications should be send for expiring SSL certificates.
    */
    'enabled'?: boolean = false;
    /**
    * At what moment in time to start alerting on SSL certificates.
    */
    'alertThreshold'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "alertThreshold",
            "baseName": "alertThreshold",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AlertSettingsSSLCertificates.attributeTypeMap;
    }
}

