/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AlertSettingsTimeBasedEscalation {
    /**
    * After how many minutes after a check starts failing an alert should be send.
    */
    'minutesFailingThreshold'?: AlertSettingsTimeBasedEscalation.MinutesFailingThresholdEnum = AlertSettingsTimeBasedEscalation.MinutesFailingThresholdEnum.NUMBER_5;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "minutesFailingThreshold",
            "baseName": "minutesFailingThreshold",
            "type": "AlertSettingsTimeBasedEscalation.MinutesFailingThresholdEnum"
        }    ];

    static getAttributeTypeMap() {
        return AlertSettingsTimeBasedEscalation.attributeTypeMap;
    }
}

export namespace AlertSettingsTimeBasedEscalation {
    export enum MinutesFailingThresholdEnum {
        NUMBER_5 = <any> 5,
        NUMBER_10 = <any> 10,
        NUMBER_15 = <any> 15,
        NUMBER_30 = <any> 30
    }
}
