/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Assertion } from './assertion';
import { BasicAuth } from './basicAuth';
import { KeyValue } from './keyValue';

export class CheckGroupCreateAPICheckDefaults {
    /**
    * The base url for this group which you can reference with the {{GROUP_BASE_URL}} variable in all group checks.
    */
    'url'?: string = '';
    'headers'?: Array<KeyValue>;
    '_queryParameters'?: Array<KeyValue>;
    /**
    * Check the main Checkly documentation on assertions for specific values like regular expressions and JSON path descriptors you can use in the \"property\" field.
    */
    'assertions'?: Array<Assertion>;
    'basicAuth'?: BasicAuth;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "Array<KeyValue>"
        },
        {
            "name": "_queryParameters",
            "baseName": "queryParameters",
            "type": "Array<KeyValue>"
        },
        {
            "name": "assertions",
            "baseName": "assertions",
            "type": "Array<Assertion>"
        },
        {
            "name": "basicAuth",
            "baseName": "basicAuth",
            "type": "BasicAuth"
        }    ];

    static getAttributeTypeMap() {
        return CheckGroupCreateAPICheckDefaults.attributeTypeMap;
    }
}

