/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CheckAlertSettings } from './checkAlertSettings';
import { EnvironmentVariable } from './environmentVariable';
import { Model1 } from './model1';

export class CheckUpdate {
    /**
    * The name of the check.
    */
    'name'?: string;
    /**
    * Determines if the check is running or not.
    */
    'activated'?: boolean = true;
    /**
    * Determines if any notifications will be send out when a check fails and/or recovers.
    */
    'muted'?: boolean = false;
    /**
    * Setting this to \"true\" will trigger a retry when a check fails from the failing region and another, randomly selected region before marking the check as failed.
    */
    'doubleCheck'?: boolean = true;
    /**
    * Allows to invert the behaviour of when a check is considered to fail. Allows for validating error status like 404.
    */
    'shouldFail'?: boolean = false;
    /**
    * An array of one or more data center locations where to run this check.
    */
    'locations'?: Array<CheckUpdate.LocationsEnum>;
    /**
    * Tags for organizing and filtering checks.
    */
    'tags'?: Array<string>;
    'alertSettings'?: CheckAlertSettings;
    /**
    * When true, the account level alert setting will be used, not the alert setting defined on this check.
    */
    'useGlobalAlertSettings'?: boolean = true;
    /**
    * The id of the check group this check is part of.
    */
    'groupId'?: number;
    /**
    * The position of this check in a check group. It determines in what order checks are run when a group is triggered from the API or from CI/CD.
    */
    'groupOrder'?: number;
    /**
    * The runtime version, i.e. fixed set of runtime dependencies, used to execute this check.
    */
    'runtimeId'?: CheckUpdate.RuntimeIdEnum;
    /**
    * List of alert channel subscriptions.
    */
    'alertChannelSubscriptions'?: Array<Model1>;
    /**
    * The type of the check.
    */
    'checkType'?: CheckUpdate.CheckTypeEnum;
    /**
    * How often the check should run in minutes.
    */
    'frequency'?: number = 10;
    /**
    * Used for setting seconds for check frequencies under 1 minutes (only for API checks) and spreading checks over a time range for frequencies over 1 minute. This works as follows: Checks with a frequency of 0 can have a frequencyOffset of 10, 20 or 30 meaning they will run every 10, 20 or 30 seconds. Checks with a frequency lower than and equal to 60 can have a frequencyOffset between 1 and a max value based on the formula \"Math.floor(frequency * 10)\", i.e. for a check that runs every 5 minutes the max frequencyOffset is 50. Checks with a frequency higher than 60 can have a frequencyOffset between 1 and a max value based on the formula \"Math.ceil(frequency / 60)\", i.e. for a check that runs every 720 minutes, the max frequencyOffset is 12. 
    */
    'frequencyOffset'?: number;
    'request': object;
    'script': string;
    /**
    * Key/value pairs for setting environment variables during check execution. These are only relevant for Browser checks. Use global environment variables whenever possible.
    */
    'environmentVariables'?: Array<EnvironmentVariable>;
    /**
    * An ID reference to a snippet to use in the setup phase of an API check.
    */
    'setupSnippetId'?: number;
    /**
    * An ID reference to a snippet to use in the teardown phase of an API check.
    */
    'tearDownSnippetId'?: number;
    /**
    * A valid piece of Node.js code to run in the setup phase.
    */
    'localSetupScript'?: string;
    /**
    * A valid piece of Node.js code to run in the teardown phase.
    */
    'localTearDownScript'?: string;
    /**
    * The response time in milliseconds where a check should be considered degraded.
    */
    'degradedResponseTime'?: number = 10000;
    /**
    * The response time in milliseconds where a check should be considered failing.
    */
    'maxResponseTime'?: number = 20000;
    /**
    * An array of one or more private locations where to run the check.
    */
    'privateLocations'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "activated",
            "baseName": "activated",
            "type": "boolean"
        },
        {
            "name": "muted",
            "baseName": "muted",
            "type": "boolean"
        },
        {
            "name": "doubleCheck",
            "baseName": "doubleCheck",
            "type": "boolean"
        },
        {
            "name": "shouldFail",
            "baseName": "shouldFail",
            "type": "boolean"
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<CheckUpdate.LocationsEnum>"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "alertSettings",
            "baseName": "alertSettings",
            "type": "CheckAlertSettings"
        },
        {
            "name": "useGlobalAlertSettings",
            "baseName": "useGlobalAlertSettings",
            "type": "boolean"
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "number"
        },
        {
            "name": "groupOrder",
            "baseName": "groupOrder",
            "type": "number"
        },
        {
            "name": "runtimeId",
            "baseName": "runtimeId",
            "type": "CheckUpdate.RuntimeIdEnum"
        },
        {
            "name": "alertChannelSubscriptions",
            "baseName": "alertChannelSubscriptions",
            "type": "Array<Model1>"
        },
        {
            "name": "checkType",
            "baseName": "checkType",
            "type": "CheckUpdate.CheckTypeEnum"
        },
        {
            "name": "frequency",
            "baseName": "frequency",
            "type": "number"
        },
        {
            "name": "frequencyOffset",
            "baseName": "frequencyOffset",
            "type": "number"
        },
        {
            "name": "request",
            "baseName": "request",
            "type": "object"
        },
        {
            "name": "script",
            "baseName": "script",
            "type": "string"
        },
        {
            "name": "environmentVariables",
            "baseName": "environmentVariables",
            "type": "Array<EnvironmentVariable>"
        },
        {
            "name": "setupSnippetId",
            "baseName": "setupSnippetId",
            "type": "number"
        },
        {
            "name": "tearDownSnippetId",
            "baseName": "tearDownSnippetId",
            "type": "number"
        },
        {
            "name": "localSetupScript",
            "baseName": "localSetupScript",
            "type": "string"
        },
        {
            "name": "localTearDownScript",
            "baseName": "localTearDownScript",
            "type": "string"
        },
        {
            "name": "degradedResponseTime",
            "baseName": "degradedResponseTime",
            "type": "number"
        },
        {
            "name": "maxResponseTime",
            "baseName": "maxResponseTime",
            "type": "number"
        },
        {
            "name": "privateLocations",
            "baseName": "privateLocations",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return CheckUpdate.attributeTypeMap;
    }
}

export namespace CheckUpdate {
    export enum LocationsEnum {
        UsEast1 = <any> 'us-east-1',
        UsEast2 = <any> 'us-east-2',
        UsWest1 = <any> 'us-west-1',
        UsWest2 = <any> 'us-west-2',
        CaCentral1 = <any> 'ca-central-1',
        SaEast1 = <any> 'sa-east-1',
        EuWest1 = <any> 'eu-west-1',
        EuCentral1 = <any> 'eu-central-1',
        EuWest2 = <any> 'eu-west-2',
        EuWest3 = <any> 'eu-west-3',
        EuNorth1 = <any> 'eu-north-1',
        EuSouth1 = <any> 'eu-south-1',
        MeSouth1 = <any> 'me-south-1',
        ApSoutheast1 = <any> 'ap-southeast-1',
        ApNortheast1 = <any> 'ap-northeast-1',
        ApEast1 = <any> 'ap-east-1',
        ApSoutheast2 = <any> 'ap-southeast-2',
        ApSoutheast3 = <any> 'ap-southeast-3',
        ApNortheast2 = <any> 'ap-northeast-2',
        ApNortheast3 = <any> 'ap-northeast-3',
        ApSouth1 = <any> 'ap-south-1',
        AfSouth1 = <any> 'af-south-1'
    }
    export enum RuntimeIdEnum {
        _202202 = <any> '2022.02',
        _202110 = <any> '2021.10',
        _202106 = <any> '2021.06',
        _202001 = <any> '2020.01'
    }
    export enum CheckTypeEnum {
        Browser = <any> 'BROWSER',
        Api = <any> 'API'
    }
}
