/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EnvironmentVariable {
    /**
    * The key of the environment variable (this value cannot be changed).
    */
    'key': string;
    /**
    * The value of the environment variable.
    */
    'value': string;
    /**
    * Used only in the UI to hide the value like a password.
    */
    'locked'?: boolean = false;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "locked",
            "baseName": "locked",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return EnvironmentVariable.attributeTypeMap;
    }
}

