/**
 * Checkly Public API
 * These are the docs for the newly released Checkly Public API.<br />If you have any questions, please do not hesitate to get in touch with us.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The API response.
*/
export class Response {
    'status'?: number;
    'statusText'?: string;
    'body'?: string;
    'headers'?: object;
    'timings'?: object;
    'timingPhases'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "statusText",
            "baseName": "statusText",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "object"
        },
        {
            "name": "timings",
            "baseName": "timings",
            "type": "object"
        },
        {
            "name": "timingPhases",
            "baseName": "timingPhases",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return Response.attributeTypeMap;
    }
}

